### ISSUE TITLE
Please add an Open Source license to the project

### ISSUE THREAD

**Issue by obscurerichard** [Shaiou/Terraform-Splunk#1]
Would you consider adding a license file to this project? This would be consistent with good [community practices](http://wiki.opensource.org/bin/Projects/How+to+apply+an+open+source+license+to+your+project) and would allow others to build upon your work with a clear set of rules for what is acceptable.

For maximum compatibility with other free software projects, please consider using MIT license, such as expressed here:

https://github.com/intel352/vagrant-shell-scripts/blob/master/LICENSE.md

(replace the copyright statement with your copyright, of course)

**Comment by Shaiou** [comment]
Sorry, did not think anyone else but me was using it. Just in case it's still useful, I aded a licence file
