### ISSUE TITLE
Search Head Cluster Logic missing for autoscaling

### ISSUE THREAD

**Issue by Mikaal** [Shaiou/Terraform-Splunk#2]
Even though the ELB has an autoscaling configuration, mapped to an image/AMI. The Search-Head cluster configuration is still needed, when a  node is added/removed.

Otherwise the replication bundle between search-heads will not occur, causing out of sync configurations as user sessions connect through the ELB.

Factor 2 needed.

With a Minimum of 3 Instances to keep HA.

**Comment by Shaiou** [comment]
Did not think anybody was using it, did not have any knowledge of search head cluster then, still don't. Feel free to create a PR from your fork if you have a fix. Anyway it's opensource licence now.

**Comment by Shaiou** [comment]
Issue won't be solved unless someone is willing to patch it for me. Anyway it's open license now
